// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"product_svc/pkg/config"
	"product_svc/pkg/db"
	"product_svc/pkg/repository"
	"product_svc/pkg/service"
	"product_svc/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (service.ProductService, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return service.ProductService{}, err
	}
	productRepository := repository.NewProductRepository(gormDB)
	productUsecase := usecase.NewProductUsecase(productRepository)
	productService := service.NewProductService(productUsecase)
	return productService, nil
}
