// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"auth_svc/pkg/config"
	"auth_svc/pkg/db"
	"auth_svc/pkg/repository"
	"auth_svc/pkg/service"
	"auth_svc/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) service.AuthService {
	gormDB := db.ConnectDatabase(cfg)
	adminRepository := repository.NewadminRepository(gormDB)
	adminUsecase := usecase.NewadminUsecase(adminRepository)
	userRepository := repository.NewUserRepository(gormDB)
	userUsecase := usecase.NewUserUsecase(userRepository)
	authService := service.NewAuthService(adminUsecase, userUsecase)
	return authService
}
